app/main/forms.py
from logging import PlaceHolder
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField, TextAreaField, SelectField
from wtforms.fields.simple import FileField
from wtforms.validators import Required

class PostForm(FlaskForm):
    title = StringField('Post title',validators=[Required()])

    summary = StringField('Summary of the post')

    description = TextAreaField('Enter the post')

    submit = SubmitField('Submit')

app/user/forms.py
from logging import PlaceHolder
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField, TextAreaField, SelectField
from wtforms.fields.simple import FileField
from wtforms.validators import Required

class blogPostsForm(FlaskForm):
    title = StringField('Post title',validators=[Required()])

    summary = StringField('Summary of the post',validators=[Required()] )

    post = TextAreaField('Enter the post details', validators=[Required()])

    image = StringField('Enter Image link', validators=[Required()])

    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
# from flask_login import LoginManager
from flask_bootstrap import Bootstrap
# from flask_mail import Mail

# login_manager = LoginManager()
# login_manager.session_protection = 'strong'
# login_manager.login_view = 'auth.login'

# mail = Mail()
def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])
    with app.app_context():
    # Initializing flask extensions
        # login_manager.init_app(app)
        # mail.init_app(app)
    # configure UploadSet
        bootstrap = Bootstrap(app)
    
        # Registering main blueprint
        from . main import main as main_blueprint
        app.register_blueprint (main_blueprint)


        #Register auth blueprint
        from .user import user as user_blueprint
        app.register_blueprint(user_blueprint,url_prefix = '/user')
    
        # # Configure request   
        from .request import configure_request
        configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import view

app/user/__init__.py
from flask import Blueprint
user = Blueprint('user',__name__)
from . import views

app/user/views.py
from flask import  render_template, redirect, url_for, session, jsonify, request
from . import user
from werkzeug.utils import secure_filename
from ..model import Post
from .forms import blogPostsForm
from ..request import new_post

@user.route('/profile', methods = ['GET'])
def user_profile():
    return render_template('user/user_profile.html')

@user.route('/create-post', methods = ['POST', 'GET'])
def create_post():
    form = blogPostsForm()
    if form.validate_on_submit():  
       title = request.form.get('title')
       image = request.form.get('image')
       post = request.form.get('post')  
       author = 'leresi'
       author_id = 'jxakkajkjakjskajkjskaj'
       summary = request.form.get('summary')

       json_data = { "title":title, "image": image, "post": post,  "author": author,  "summary": summary, "author_id": author_id}

       new_post('/pitch', json_data)
    return render_template('user/new_post.html', postsForm=form )

@user.route('/posts', methods = ['GET'])
def get_posts():
    return render_template('user/user_blog_posts.html')

@user.route('/blog-activities', methods = ['GET'])
def blog_activities():
    return render_template('user/blog_activities.html')

app/templates/all_post.html
{% extends 'index.html'%}

{% block content %}
<div id="main-content" class="blog-page">
    <div class="container">
        <div class="row clearfix">
            <div class="col-lg-8 col-md-12 left-box">
                {% for post in posts %}
                <div class="card single_post">
                    <div class="body">
                        <div class="img-post">
                            {% if post.image %}
                            <img class="d-block img-fluid" src="{{post.image}}" alt="image">
                            {% elif post.image !='.jpg' %}
                            <img class="d-block img-fluid" src="https://via.placeholder.com/800x280/FFB6C1/000000" alt="image">
                            {% endif %}
                        </div>
                        <h3><a href="blog-details.html">{{post.title}}</a></h3>
                        <p>{{post.summary}}</p>
                    </div>
                    <div class="footer">
                        <div class="actions">
                            <a href="{{url_for('main.get_post', id = post.id)}}" class="btn btn-outline-secondary btn-sm">Continue Reading</a>
                        </div>
                        <ul class="stats">
                            <li><a href=""></a><small>comment</small></a></li>
                            <li>posted {{post.posted}}</li>
                            <li>author {{post.author}}</li>
                        </ul>
                    </div>
                </div> 
                {% endfor %} 

            </div>
            <div class="col-lg-4 col-md-12 right-box">
                <div class="card">
                    <div class="body search">
                        <div class="input-group m-b-0">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-search"></i></span>
                            </div>
                            <input type="text" class="form-control" placeholder="Search...">                                    
                        </div>
                    </div>
                </div>
                
                <div class="card">
                    <div class="header">
                        <h2>Quote of the day</h2>                        
                    </div>
                    <div class="body widget popular-post">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="single_post">
                                    <p class="m-b-0">{{quote.quote}}</p>

                                    <span><i><strong>by:  {{quote.author}}</strong></i></span>                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="header">
                        <h2>Email Newsletter <small>Get our products/news earlier than others, let’s get in touch.</small></h2>
                    </div>
                    <div class="body widget newsletter">                        
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Enter Email">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="icon-paper-plane"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <title>blog</title>
</head>
<body>
    <header class="header-area overlay">
        <nav class="navbar navbar-expand-sm navbar-dark  fixed-top">
            <!-- Toggler/collapsibe Button -->
            <div class="container-fluid">
                <a href="/" class="navbar-brand">
                    <span style="font-family: cursive;">
                        LERESI BLOG
                    </span>
                </a>
                <button class="navbar-toggler collapsed ms-auto ms-sm-2" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle Navigation">
                    <span class="menu-icon-bar"></span>
                    <span class="menu-icon-bar"></span>
                    <span class="menu-icon-bar"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-end" id="main-nav">
                    <ul class="navbar-nav ms-2 align-items-end">
                         <li><a href="/" class="nav-item nav-link active"><small>Home</small></a></li>
                        <li><a href="/" class="nav-item nav-link"><small>Recent Posts</small></a></li>
                    </ul>
                      <div class="btn-group dropdown " style="margin-right: 5vw;">
                    <button type="button" class="btn btn-primary dropdown-toggle text-white" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="far fa-user"></i> 
                    account
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        <li><a href="{{url_for('user.create_post')}}" class="dropdown-item" type="button">create blog</a></li>
                      </ul>
                  </div>
                </div>
              
        
      </div>
            </div>
        </nav>
        
    </header> 
    {% block content %}  
    
    {% endblock %} 
</body>
</html>

app/templates/user/blog_activities.html
{% extends 'user/user_profile.html'%}

{% block user_actions %} 
	
    <div class="tab-pane animated fadeInRight" id="user-activities">
        <div class="scroll-user-widget">
            <ul class="media-list">
                <li class="media">
                    <a href="#fakelink">
                    <p><strong>John Doe</strong> Uploaded a photo <strong>"DSC000254.jpg"</strong>
                    <br><i>2 minutes ago</i></p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    {% endblock %}

app/templates/user/new_post.html
{% extends 'user/user_profile.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block user_actions %} 

<div class="container">
    {{ wtf.quick_form(postsForm) }}

</div>					
{% endblock %}

app/templates/user/user_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"> 
    <link rel="stylesheet" href="{{ url_for('static', filename='user.css') }}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<title>user</title>
</head>
<body>
    {% block user_content %}  
    
    {% endblock %} 
</body>
</html>

app/templates/user/user_blog_posts.html
{% extends 'user/user_profile.html'%}

{% block user_actions %} 
<div class="tab-pane animated fadeInRight" id="mymessage">
    <div class="scroll-user-widget">
        <ul class="media-list">
          <li class="media">
            <a class="pull-left" href="#fakelink">
              <img class="media-object user-message" src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="Avatar">
            </a>
            <div class="media-body">
              <h4 class="media-heading"><a href="#fakelink">John Doe</a> <small>Just now</small></h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
            </div>
          </li>
        </ul>
    </div>
</div>
{% endblock %}

app/templates/user/user_profile.html
{% extends 'user/user_base.html'%}

{% block user_content %}
<div class="container">
<div class="content-page">
    <div class="profile-banner" style="background:url(https://bootdey.com/img/Content/bg1.jpg);">
		<div class="col-sm-3 avatar-container">
			<img src="https://upload.wikimedia.org/wikipedia/commons/f/f4/User_Avatar_2.png" class="img-circle profile-avatar" alt="User avatar">
		</div>
		<div class="col-sm-12 profile-actions text-right">
			<a href="/" type="button" class="btn btn-success btn-sm"><i class="fa fa-check"></i> return to blog</a>
		</div>
	</div>
    <div class="content">

		<div class="row">
			<div class="col-sm-3">
				<!-- Begin user profile -->
				<div class="text-center user-profile-2" style="margin-top:120px">
					<ul class="list-group">
                      <li class="list-group-item">
    					<h4>Anonymous, <b>User</b></h4>
						<h5><small>Anonymous@gmail.com</small></h5>
					  </li>
				
					  <li class="list-group-item">
						<span class="badge">245</span>
						posts
					  </li>

					</ul>
				</div>
			</div>
			
			<div class="col-sm-9">
				<div class="widget widget-tabbed">
					<nav class="nav nav-pills nav-justified">
						<a class="nav-item nav-link" href="{{url_for('user.get_posts')}}" data-toggle="tab"><i class="fa fa-user"></i> my posts</a>
						<a class="nav-item nav-link" href="{{url_for('user.create_post')}}" data-toggle="tab"><i class="fa fa-pencil"></i> create post</a>
						<a class="nav-item nav-link" href="{{url_for('user.blog_activities')}}" data-toggle="tab"><i class="fa fa-laptop"></i>  blog activities</a>
					  </nav> 
					<div class="card">
						<div class="card-body">
							{% block user_actions %} 
						
							{% endblock %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>	
</div>
{% endblock %}

app/templates/view_blog_post.html
{% extends 'index.html'%}

{% block content %}
<div class="container">
    <div class="row clearfix">
        <div class="col-lg-8 col-md-12 left-box">
            <div class="card single_post">
                <div class="body">
                    <div class="img-post">
                        {% if post.image %}
                        <img class="d-block img-fluid" src="{{post.image}}" alt="image">
                        {% elif post.image !='.jpg' %}
                        <img class="d-block img-fluid" src="https://via.placeholder.com/800x280/FFB6C1/000000" alt="image">
                        {% endif %}
                    </div>
                    <h3><a href="blog-details.html">{{post.title}}</a></h3>
                    <p>{{post.post}}</p>
                </div>
            </div> 
        </div>
        <div class="col-lg-4 col-md-12 right-box">
            <div class="card">
                <div class="body search">
                    <div class="input-group m-b-0">
                      
                        <input type="text" class="form-control" placeholder="leave a comment">     
                            <button class="btn btn-primary btn-group-sm ml-2">comment</button>
                               
                    </div>
                </div>
            </div>
            
            <div class="card">
                <div class="body widget popular-post">
                    <div class="row">
                        <div class="col-lg-12">
                            <h2>Post summary</h2>                        
                            <div class="single_post">
                                <p class="m-b-0"><i><strong>{{post.summary}}</strong></i></p>
                                <span><i><strong>author:  {{post.author}}</strong></i></span> <br>                   
                                <span><i><strong>posted:  {{post.posted}}</strong></i></span>                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}